services:
  influxdb:
    image: influxdb:2.7-alpine
    environment:
    - DOCKER_INFLUXDB_INIT_MODE=setup
    - DOCKER_INFLUXDB_INIT_USERNAME=admin
    - DOCKER_INFLUXDB_INIT_PASSWORD=admin_password
    - DOCKER_INFLUXDB_INIT_ORG=monitoring
    - DOCKER_INFLUXDB_INIT_BUCKET=energy-metrics
    - DOCKER_INFLUXDB_INIT_RETENTION=104w
    - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=secret_admin_token
    ports:
      - "28086:8086"
  grafana:
    image: grafana/grafana-oss:12.0.1
    ports:
      - "13000:3000"
    depends_on:
      - influxdb
    volumes:
    - ./grafana/provisioning:/etc/grafana/provisioning
    - ./grafana/lib/dashboards:/var/lib/grafana/dashboards
  octograph-query:
    image: yansonb/octograph-query:latest
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_ORG=monitoring
      - INFLUXDB_BUCKET=energy-metrics
      - INFLUXDB_TOKEN=secret_admin_token
    ports:
      - "18080:8080"
    depends_on:
      - influxdb

networks:
  default:
    name: octograph
