{
 "title": "Energy Usage",
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "location",
    "label": "Location",
    "query": "SHOW TAG VALUES WITH KEY = \"location\""
   },
   { "name": "vat", "label": "VAT", "query": "inc,exc" },
   { "name": "resolution", "label": "Resolution", "query": "30m,1h,2h,4h,6h,12h,1d,7d" }
  ]
 },
 "panels": [
  { "title": "Electricity Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Electricity Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT sum(\"usage_kwh\") FROM \"electricity_consumption\" WHERE $timeFilter AND location = '$location'",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT sum(\"total_cost_${vat}_vat_pence\") / 100 FROM \"electricity_consumption\" WHERE $timeFilter AND location = '$location'",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Average",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT SUM(\"usage_kwh\") / ((${__to} - ${__from}) / (1000*60*60*24)) FROM \"electricity_consumption\" WHERE $timeFilter AND location = '$location'",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Average",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT SUM(\"total_cost_${vat}_vat_pence\") / ((${__to} - ${__from}) / (1000*60*60*24)) / 100 FROM \"electricity_consumption\" WHERE $timeFilter AND location = '$location'",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Unit Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "p" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT\nsum(\"usage_cost_${vat}_vat_pence\")\n/\nsum(\"usage_kwh\")\nFROM \"electricity_consumption\" WHERE $timeFilter AND location = '$location'",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "...inc Standing Charge",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "p" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT\nsum(\"total_cost_${vat}_vat_pence\")\n/\nsum(\"usage_kwh\")\nFROM \"electricity_consumption\" WHERE $timeFilter AND location = '$location'",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electricity Usage and Cost",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Standing Charge Cost",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT SUM(\"standing_charge_cost_${vat}_vat_pence\") / 100 FROM \"electricity_consumption\" WHERE $timeFilter AND location = '$location' GROUP BY time($resolution) fill(none)",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Usage Cost",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT SUM(\"usage_cost_${vat}_vat_pence\") / 100 FROM \"electricity_consumption\" WHERE $timeFilter AND location = '$location' GROUP BY time($resolution) fill(none)",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Usage",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT SUM(\"usage_kwh\") FROM \"electricity_consumption\" WHERE $timeFilter AND location = '$location' GROUP BY time($resolution) fill(none)",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Electricity Pricing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Property Address",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT MIN(\"usage_kwh\"), \n  \"property_address_line_1\"::tag, \n  \"property_address_line_2\"::tag,\n  \"property_address_line_3\"::tag,\n  \"property_postcode\"::tag\nFROM \"electricity_consumption\"\nWHERE $timeFilter AND location = '$location'",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unit Pricing",
   "type": "trend",
   "description": "Yesterday / Today / Tomorrow Pricing",
   "gridPos": { "h": 6, "w": 14, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "price",
     "query": "SELECT MEAN(\"unit_price_${vat}_vat_price\")  FROM \"electricity_pricing\" WHERE time >= now() - 2d AND time < now() + 2d AND location = '$location' GROUP BY time(30m) fill(none)"
    }
   ]
  },
  {
   "title": "Tariff Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "p" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT MIN(\"unit_price_inc_vat_price\"), \"tariff_code\"::tag   FROM \"electricity_pricing\" WHERE $timeFilter AND location = '$location'",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Standing Charge",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "p" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT MEAN(\"standing_charge_${vat}_vat_price\")  FROM \"electricity_pricing\" WHERE $timeFilter AND location = '$location'",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Unit Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "p" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT MEAN(\"unit_price_${vat}_vat_price\")  FROM \"electricity_pricing\" WHERE $timeFilter AND location = '$location'",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pricing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "p" } },
   "targets": [
    {
     "alias": "Unit Price",
     "query": "SELECT MEAN(\"unit_price_${vat}_vat_price\")  FROM \"electricity_pricing\" WHERE $timeFilter AND location = '$location' GROUP BY time($resolution) fill(none)"
    },
    {
     "alias": "Daily Standing Charge",
     "query": "SELECT MEAN(\"standing_charge_${vat}_vat_price\")  FROM \"electricity_pricing\" WHERE $timeFilter AND location = '$location' GROUP BY time($resolution) fill(none)"
    },
    {
     "alias": "Unit Cost",
     "query": "SELECT\n  sum(\"usage_cost_${vat}_vat_pence\") / sum(\"usage_kwh\")\nFROM \"electricity_consumption\"\nWHERE $timeFilter AND location = '$location'\nGROUP BY time($resolution) fill(none)"
    }
   ]
  },
  {
   "title": "Gas Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Gas Used",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "electricity",
       "query": "SELECT sum(\"usage_kwh\") FROM \"gas_consumption\" WHERE $timeFilter AND location = '$location'",
       "select": [
        [
         { "params": [ "consumption" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Daily Average",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "electricity",
       "query": "SELECT SUM(\"usage_kwh\") / ((${__to} - ${__from}) / (1000*60*60*24)) FROM \"gas_consumption\" WHERE $timeFilter AND location = '$location'",
       "select": [
        [
         { "params": [ "consumption" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total Cost",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "electricity",
       "query": "SELECT sum(\"total_cost_${vat}_vat_pence\") / 100 FROM \"gas_consumption\" WHERE $timeFilter AND location = '$location'",
       "select": [
        [
         { "params": [ "consumption" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Daily Average",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "electricity",
       "query": "SELECT SUM(\"total_cost_${vat}_vat_pence\") / ((${__to} - ${__from}) / (1000*60*60*24)) / 100 FROM \"gas_consumption\" WHERE $timeFilter AND location = '$location'",
       "select": [
        [
         { "params": [ "consumption" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Gas Usage and Cost",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "alias": "Standing Charge Cost",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "electricity",
       "query": "SELECT SUM(\"standing_charge_cost_${vat}_vat_pence\") / 100 FROM \"gas_consumption\" WHERE $timeFilter AND location = '$location' GROUP BY time($resolution) fill(none)",
       "select": [
        [
         { "params": [ "cost" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Usage Cost",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "electricity",
       "query": "SELECT SUM(\"usage_cost_${vat}_vat_pence\") / 100 FROM \"gas_consumption\" WHERE $timeFilter AND location = '$location' GROUP BY time($resolution) fill(none)",
       "select": [
        [
         { "params": [ "cost" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Usage",
       "groupBy": [
        { "params": [ "30m" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "electricity",
       "query": "SELECT SUM(\"usage_kwh\") FROM \"gas_consumption\" WHERE $timeFilter AND location = '$location' GROUP BY time($resolution) fill(none)",
       "select": [
        [
         { "params": [ "consumption" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Gas Pricing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Property Address",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "electricity",
       "query": "SELECT MIN(\"usage_kwh\"), \n  \"property_address_line_1\"::tag, \n  \"property_address_line_2\"::tag,\n  \"property_address_line_3\"::tag,\n  \"property_postcode\"::tag\nFROM \"gas_consumption\"\nWHERE $timeFilter AND location = '$location'",
       "select": [
        [
         { "params": [ "consumption" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Pricing",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 14, "x": 4, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "p" } },
     "targets": [
      {
       "alias": "Unit Price",
       "query": "SELECT MEAN(\"unit_price_${vat}_vat_price\")  FROM \"gas_pricing\" WHERE $timeFilter AND location = '$location' GROUP BY time($resolution) fill(none)"
      },
      {
       "alias": "Daily Standing Charge",
       "query": "SELECT MEAN(\"standing_charge_${vat}_vat_price\")  FROM \"gas_pricing\" WHERE $timeFilter AND location = '$location' GROUP BY time($resolution) fill(none)"
      }
     ]
    },
    {
     "title": "Tariff Code",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 18, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "p" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "electricity",
       "query": "SELECT MIN(\"unit_price_inc_vat_price\"), \"tariff_code\"::tag   FROM \"gas_pricing\" WHERE $timeFilter AND location = '$location'",
       "select": [
        [
         { "params": [ "consumption" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Daily Standing Charge",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "p" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "electricity",
       "query": "SELECT MEAN(\"standing_charge_${vat}_vat_price\")  FROM \"gas_pricing\" WHERE $timeFilter AND location = '$location'",
       "select": [
        [
         { "params": [ "consumption" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Average Unit Price",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "p" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "electricity",
       "query": "SELECT MEAN(\"unit_price_${vat}_vat_price\")  FROM \"gas_pricing\" WHERE $timeFilter AND location = '$location'",
       "select": [
        [
         { "params": [ "consumption" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}